### PR TITLE
Increase compat for CairoMakie

### PR DESCRIPTION
**Pull request by sefffal**
Increase combat to include support for Makie 0.21 (via CairoMakie 0.12). Not yet tested but let's see what CI says.

### CODE REVIEW

**Comment by alexandrebouchard** [comment]
Thank you!!

**Comment by sefffal** [comment]
Bump!

**Comment by miguelbiron** [comment]
hey @sefffal -- sorry for the delay. Would you mind rebasing your branch? Then I can merge once tests pass.

**Comment by miguelbiron** [comment]
Scratch that: it looks that I already bumped that compat in this commit

https://github.com/Julia-Tempering/InferenceReport.jl/commit/f4ba0171e3d40cdf230a6de3086b468f8a432edb

**Comment by sefffal** [comment]
Ah, thanks then! We can close this.

**Pull request closed without merging**
